export const state = {
  rawData: [],
  filteredData: [],
  costChart: null,
  modelChart: null,
  table: null,
  granularity: 'day',
  metric: 'requests',
  modelColorMap: {},
  hasUsers: false,
  tableHasUsers: null,
  hiddenTokenComponents: new Set(),
  budgetMonthly: null,
  lastImportAt: null,
  periodPreset: 'all',
  compareEnabled: false,
  compareChart: null,
  efficiencyChart: null,
};
